Repository DeveloperAcademy-POSTECH/MacC-Team10-OFO, pull requests merged in 2023-10, with the labels that each got.

#10 [Feat] 데이터 모델 설계
  Projects/Core/Sources/Models/CaloriesLevel.swift
  Projects/Core/Sources/Models/DistanceCoveredLevel.swift
  Projects/Core/Sources/Models/Player.swift
  Projects/Core/Sources/Models/Record.swift
Labels: ✨ Feature, ✈️ ASAP

#16 [Feat] 도넛 차트 공통 컴포넌트 및 갤러리 뷰(레코드) 구현
  Projects/Common/Resources/Images.xcassets/23_8_1.imageset/23_8_1.pdf
  Projects/Common/Resources/Images.xcassets/23_8_1.imageset/Contents.json
  Projects/Common/Resources/Images.xcassets/23_8_2.imageset/23_8_2.pdf
  Projects/Common/Resources/Images.xcassets/23_8_2.imageset/Contents.json
  Projects/Common/Resources/Images.xcassets/23_8_3.imageset/23_8_3.pdf
  Projects/Common/Resources/Images.xcassets/23_8_3.imageset/Contents.json
  Projects/Common/Resources/Images.xcassets/23_8_4.imageset/23_8_4.pdf
  Projects/Common/Resources/Images.xcassets/23_8_4.imageset/Contents.json
  Projects/Common/Resources/Images.xcassets/23_8_5.imageset/23_8_5.pdf
  Projects/Common/Resources/Images.xcassets/23_8_5.imageset/Contents.json
  Projects/Common/Resources/Images.xcassets/23_8_6.imageset/23_8_6.pdf
  Projects/Common/Resources/Images.xcassets/23_8_6.imageset/Contents.json
  Projects/Common/Resources/Images.xcassets/23_8_7.imageset/23_8_7.pdf
  Projects/Common/Resources/Images.xcassets/23_8_7.imageset/Contents.json
  Projects/Common/Resources/Images.xcassets/23_9_1.imageset/23_9_1.pdf
  Projects/Common/Resources/Images.xcassets/23_9_1.imageset/Contents.json
  Projects/Common/Resources/Images.xcassets/23_9_2.imageset/23_9_2.pdf
  Projects/Common/Resources/Images.xcassets/23_9_2.imageset/Contents.json
  Projects/Common/Resources/Images.xcassets/23_9_3.imageset/23_9_3.pdf
  Projects/Common/Resources/Images.xcassets/23_9_3.imageset/Contents.json
  Projects/Common/Resources/Images.xcassets/23_9_4.imageset/23_9_4.pdf
  Projects/Common/Resources/Images.xcassets/23_9_4.imageset/Contents.json
  Projects/Common/Resources/Images.xcassets/23_9_5.imageset/23_9_5.pdf
  Projects/Common/Resources/Images.xcassets/23_9_5.imageset/Contents.json
  Projects/Common/Resources/Images.xcassets/23_9_6.imageset/23_9_6.pdf
  Projects/Common/Resources/Images.xcassets/23_9_6.imageset/Contents.json
  Projects/Common/Resources/Images.xcassets/Contents.json
  Projects/Common/Sources/Extension/Color+.swift
  Projects/Common/Sources/Extension/UINavigationViewController+.swift
  Projects/Common/Sources/Helper/Dummy2.swift
  Projects/Common/Sources/View/DonutChartView.swift
  Projects/Feature/Sources/Media.xcassets/23_8_1.imageset/23_8_1.pdf
  Projects/Feature/Sources/Media.xcassets/23_8_1.imageset/Contents.json
  Projects/Feature/Sources/Media.xcassets/Contents.json
  Projects/Feature/Sources/View/RecordView.swift
Labels: ✨ Feature

#15 [Feat] 메인 화면 UI 및 기능 구현
  Projects/Feature/Sources/View/MainView.swift
Labels: ✨ Feature

#14 [Feat] 인증 샷 삽입/수정/삭제 기능 구현
  Projects/Feature/Sources/ObservedObject/RecordDetailObservedObject.swift
  Projects/Feature/Sources/View/RecordDetailView.swift
Labels: ✨ Feature

#23 feat: 하단 탭뷰 추가(#21)
  Projects/Feature/Sources/SwiftUIView.swift
Labels: ✈️ ASAP

#25 [Feat] 갤러리 뷰와 디테일 뷰 연결
  Projects/Core/Sources/Models/Record.swift
  Projects/Feature/Sources/ObservedObject/RecordDetailObservedObject.swift
  Projects/Feature/Sources/ObservedObject/RecordObservedObject.swift
  Projects/Feature/Sources/View/RecordDetailView.swift
  Projects/Feature/Sources/View/RecordView.swift
Labels: ✨ Feature

#27 [Feat] RecordDetailView 도넛뷰, UI 구현
  Projects/Core/Sources/Models/Record.swift
  Projects/Feature/Sources/ObservedObject/RecordDetailObservableObject.swift
  Projects/Feature/Sources/ObservedObject/RecordObservableObject.swift
  Projects/Feature/Sources/View/RecordDetailView.swift
  Projects/Feature/Sources/View/RecordView.swift
Labels: ✨ Feature

#26 [Feat] 기록 요약 UI 구현, Mock 데이터 연결
  Projects/Feature/Sources/ObservedObject/MainDetailViewObservedObject.swift
  Projects/Feature/Sources/View/MainDetailView.swift
Labels: ✨ Feature

#29 [Release] 테스트 플라이트 배포
  Projects/App/Project.swift
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/App/Resources/Assets.xcassets/Contents.json
  Projects/Core/Sources/Models/Record.swift
  Projects/Feature/Sources/ObservedObject/MainDetailViewObservedObject.swift
  Projects/Feature/Sources/ObservedObject/MainObservableObject.swift
  Projects/Feature/Sources/ObservedObject/RecordObservableObject.swift
  Projects/Feature/Sources/View/MainDetailView.swift
  Projects/Feature/Sources/View/MainView.swift
  Projects/Feature/Sources/View/RecordView.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: 🍎 Release

#31 Feature/#30
  Projects/Feature/Sources/SwiftUIView.swift
  Projects/WatchApp/Project.swift
  Projects/WatchApp/Resources/Dummy.swift
  Projects/WatchApp/Sources/Dummy.swift
  Projects/WatchApp/Tests/Dummy.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: ✈️ ASAP, ⚙️ Chore

#33 [ Chore] 메인앱, 와치 연동
  Projects/App/Project.swift
  Projects/WatchApp/Project.swift
  Projects/WatchApp/Sources/ContentsView.swift
  Projects/WatchApp/Sources/WatchApp.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+Project.swift
Labels: ✈️ ASAP, ⚙️ Chore

#34 [Chore] Tuist Watch 세팅, LaunchScreen 문제 해결
  Projects/App/Project.swift
  Projects/App/WatchApp/Dummy.swift
  Projects/App/WatchExtension/Dummy.swift
  Projects/Common/Project.swift
  Projects/Core/Project.swift
  Projects/Feature/Project.swift
  Projects/WatchApp/Project.swift
  Projects/WatchApp/Sources/ContentsView.swift
  Projects/WatchApp/Sources/WatchApp.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Tuist/ProjectDescriptionHelpers/Target+extensions.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+Project.swift
Labels: ✈️ ASAP, ⚙️ Chore
