Repository DeveloperAcademy-POSTECH/MacC-Team10-OFO, pull requests merged in 2023-11, with the labels that each got.

#40 [Feat] Watch에서 헬스 데이터 추적
  Projects/App/Project.swift
  Projects/WatchApp/Project.swift
  Projects/WatchApp/Sources/Manager/WorkoutManager.swift
  Projects/WatchApp/Sources/View/ControlsView.swift
  Projects/WatchApp/Sources/View/ElapsedTimeView.swift
  Projects/WatchApp/Sources/View/MetricsView.swift
  Projects/WatchApp/Sources/View/SessionPagingView.swift
  Projects/WatchApp/Sources/View/StartView.swift
  Projects/WatchApp/Sources/View/SummaryView.swift
  Projects/WatchApp/Sources/WatchApp.swift
Labels: ✨ Feature, ⚙️ Chore

#43 bug: 기록 텝 들어가지지 않는 오류 해결(#42)
  Projects/App/Project.swift
Labels: 🐜 Bug, ⚙️ Chore

#44 [Feat] SwiftDataManager 구현, SwiftData 도입, Observable로 변경
  Projects/Core/Sources/Manager/SwiftData/SwiftDataManager.swift
  Projects/Core/Sources/Models/DistanceCoveredLevel.swift
  Projects/Core/Sources/Models/Match.swift
  Projects/Core/Sources/Models/Player.swift
  Projects/Core/Sources/Models/Record.swift
  Projects/Feature/Sources/ObservedObject/MainObservable.swift
  Projects/Feature/Sources/ObservedObject/MainObservableObject.swift
  Projects/Feature/Sources/ObservedObject/RecordObservable.swift
  Projects/Feature/Sources/ObservedObject/RecordObservableObject.swift
  Projects/Feature/Sources/SwiftUIView.swift
  Projects/Feature/Sources/View/MainView.swift
Labels: ✨ Feature

#48 [Chore] Bundle ID, 팀 설정(#47)
  Projects/App/Project.swift
  Projects/WatchApp/Project.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: ✈️ ASAP, ⚙️ Chore

#49 [Fea] HealthStore 데이터, SwiftData 연동 테스트(#46)
  Projects/Core/Sources/Models/Match.swift
  Projects/Core/Sources/WorkoutManager.swift
  Projects/Feature/Sources/ObservedObject/RecordObservable.swift
  Projects/Feature/Sources/SwiftUIView.swift
  Projects/Feature/Sources/View/RecordView.swift
Labels: ✨ Feature, ✈️ ASAP
